<?php

/**
 * Implements hook_form_alter()
 */
function islandora_cron_pathauto_form_alter(&$form , &$form_state, $form_id) {
  if ($form_id == 'pathauto_settings_form') {
      
    $options = array(
      0 => 'Never',
      1 => '1 hour',
      2 => '3 hours',
      3 => '6 hours',
      4 => '12 hours',
      5 => '1 day',
      6 => '1 week',
    );
      
    $form['schedule_cron'] = array(
      '#title'         => t('Cron URL Alias'),
      '#required'      => FALSE,
      '#description'   => t("Cron Schedule for Bulk Generate"),
      '#type'          => 'select',
      '#options'       => $options,
      '#default_value' => variable_get("cron_schedule", 'Never'),
      '#weight'        => -2,
    );
    array_push( $form['#submit'], 'islandora_cron_pathauto_form_submit');
  }
}

function islandora_cron_pathauto_form_submit($form, &$form_state) { 
    variable_set("cron_schedule", $form_state['values']['schedule_cron']);
}