<?php

/**
 * Implements hook_form_alter()
 */
function islandora_cron_pathauto_form_alter(&$form , &$form_state, $form_id) {
  if ($form_id == 'pathauto_settings_form') {
      
    $options = array(
      0 => 'Never',
      1 => '1 hour',
      2 => '3 hours',
      3 => '6 hours',
      4 => '12 hours',
      5 => '1 day',
      6 => '1 week',
    );
    $form['cron_group'] = array(
        '#type'        => 'fieldset',
        '#title'       => t('Cron Schedule'),
        '#weight'      => -3,
    );
    
    $form['cron_group']['schedule_cron_options'] = array(
      '#title'         => t('Select the types of paths for which to regularly cron URL alises'),
      '#type'          => 'checkboxes',
      '#options'       => array(),
      '#default_value' => array(),
    );
    
    $form['cron_group']['schedule_cron'] = array(
      '#title'         => t('Run cron every'),
      '#required'      => FALSE,
      '#description'   => t("Cron Schedule for Bulk Generate"),
      '#type'          => 'select',
      '#options'       => $options,
      '#default_value' => variable_get("cron_schedule", 'Never'),
    );
    
    $form['cron_group']['cron_submit'] = array(
      '#type'          => 'submit',
      '#value'         => t('Run Cron Now'),
    );

    $pathauto_settings = module_invoke_all('pathauto', 'settings');
    foreach ($pathauto_settings as $settings) {
      if (!empty($settings->batch_update_callback)) {
        $form['#update_callbacks'][$settings->batch_update_callback] = $settings;
        $form['cron_group']['schedule_cron_options']['#options'][$settings->batch_update_callback] = $settings->groupheader;
      }
    }
    $form['cron_group']['schedule_cron_options']['#default_value'] = array(1);
    array_push( $form['#submit'], 'islandora_cron_pathauto_form_submit');
  }
}

function islandora_cron_pathauto_form_submit($form, &$form_state) { 
    variable_set("cron_schedule", $form_state['values']['schedule_cron']);
}